from __future__ import print_function

import argparse
import codecs
import difflib
import json
import os
import re
from datetime import datetime

from PIL import Image


SHEET_HINTS = (
    "tileset",
    "tile set",
    "tilesheet",
    "tile sheet",
    "spritesheet",
    "sprite sheet",
    "atlas",
    "autotile",
    "singles",
)

ANIMATION_HINTS = (
    "animated",
    "animation",
    "idle",
    "movement",
    "take_damage",
    "portal",
    "waterfall",
    "trap",
    "door",
    "switch",
)

TILE_CELL_SIZES = (16, 32, 24, 8, 48, 64, 12)
FALLBACK_CELL_SIZES = (16, 8, 32, 24, 12, 48, 64)
TOKEN_STOPWORDS = set(
    [
        "png",
        "jpg",
        "jpeg",
        "tileset",
        "tilesheet",
        "sheet",
        "sprite",
        "spritesheet",
        "final",
        "copy",
        "new",
        "v2",
        "v3",
        "ver",
    ]
)


def parse_args():
    parser = argparse.ArgumentParser(description="Build deterministic tileset/spritesheet registry.")
    parser.add_argument(
        "--manifest",
        default="assets/organized/asset_manifest.json",
        help="Path to asset manifest JSON generated by reorganize-art-assets.ps1",
    )
    parser.add_argument(
        "--output",
        default="assets/organized/tileset_registry.json",
        help="Output registry JSON path",
    )
    parser.add_argument(
        "--overrides",
        default="assets/organized/tileset_overrides.json",
        help="Optional per-sheet overrides JSON path",
    )
    parser.add_argument(
        "--psd-root",
        default="C:\\Users\\ericc\\Desktop\\PSD",
        help="Optional PSD root used for best-effort matching hints",
    )
    parser.add_argument(
        "--min-confidence",
        type=float,
        default=0.45,
        help="Minimum confidence needed to include a candidate in auto-slice queue",
    )
    return parser.parse_args()


def sanitize_token(value):
    token = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return token or "asset"


def tokenize(value):
    parts = re.split(r"[^a-z0-9]+", value.lower())
    tokens = [p for p in parts if p and p not in TOKEN_STOPWORDS]
    return tokens


def token_overlap_score(tokens_a, tokens_b):
    set_a = set(tokens_a)
    set_b = set(tokens_b)
    if not set_a or not set_b:
        return 0.0
    inter = float(len(set_a.intersection(set_b)))
    union = float(len(set_a.union(set_b)))
    return inter / union if union > 0 else 0.0


def build_asset_id(target_relative):
    posix_path = target_relative.replace("\\", "/")
    without_ext = os.path.splitext(posix_path)[0]
    return sanitize_token(without_ext)


def guess_cell_size(width, height, prefer_tiles):
    sizes = TILE_CELL_SIZES if prefer_tiles else FALLBACK_CELL_SIZES
    for size in sizes:
        if width % size == 0 and height % size == 0 and (width // size) * (height // size) >= 4:
            return size
    return 16 if width >= 16 and height >= 16 else max(1, min(width, height))


def infer_kind(category, context_text):
    if "tile" in category or "tileset" in context_text or "tilesheet" in context_text:
        return "tile_sheet"
    if "animated objects spritesheets" in context_text or any(hint in context_text for hint in ANIMATION_HINTS):
        return "animation_sheet"
    if "sprite" in context_text:
        return "sprite_sheet"
    return "unknown_sheet"


def compute_confidence(category, context_text, width, height, cell_size):
    score = 0.0
    if category == "level/tiles":
        score += 0.60
    if any(hint in context_text for hint in SHEET_HINTS):
        score += 0.22
    if "animated objects spritesheets" in context_text:
        score += 0.22
    if width % cell_size == 0 and height % cell_size == 0:
        score += 0.10
    if "ui" in category and "tileset" not in context_text and "tilesheet" not in context_text:
        score -= 0.12
    return max(0.0, min(1.0, score))


def is_sheet_candidate(category, context_text, width, height):
    if category == "level/tiles":
        return True
    if any(hint in context_text for hint in SHEET_HINTS):
        return True
    if "animated objects spritesheets" in context_text:
        return True
    return width >= 128 and height >= 64 and width % 8 == 0 and height % 8 == 0 and "ui-png-" not in context_text


def resolve_repo_root(manifest_path):
    return os.path.dirname(os.path.dirname(os.path.dirname(manifest_path)))


def read_dimensions(repo_root, target_relative):
    image_path = os.path.join(repo_root, target_relative.replace("/", os.sep))
    image = Image.open(image_path)
    try:
        return image.size
    finally:
        image.close()


def ensure_parent(path):
    parent = os.path.dirname(path)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)


def read_json(path):
    with codecs.open(path, "r", "utf-8-sig") as f:
        return json.load(f)


def write_json(path, payload):
    ensure_parent(path)
    with codecs.open(path, "w", "utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=False)
        f.write("\n")


def utc_now_iso():
    return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def load_overrides(path):
    if not os.path.exists(path):
        return {"assetOverrides": {}, "pathOverrides": {}, "patternOverrides": []}
    data = read_json(path)
    return {
        "assetOverrides": data.get("assetOverrides", {}),
        "pathOverrides": data.get("pathOverrides", {}),
        "patternOverrides": data.get("patternOverrides", []),
    }


def apply_overrides(base_data, overrides, asset_id, target_relative):
    merged = dict(base_data)
    target_norm = target_relative.replace("\\", "/")

    asset_override = overrides["assetOverrides"].get(asset_id)
    if isinstance(asset_override, dict):
        merged.update(asset_override)

    path_override = overrides["pathOverrides"].get(target_norm)
    if isinstance(path_override, dict):
        merged.update(path_override)

    for pattern_rule in overrides["patternOverrides"]:
        needle = pattern_rule.get("contains")
        override = pattern_rule.get("override")
        if needle and isinstance(override, dict) and needle in target_norm:
            merged.update(override)

    return merged


def collect_psd_candidates(psd_root):
    if not psd_root or not os.path.isdir(psd_root):
        return []

    candidates = []
    for root, _, files in os.walk(psd_root):
        for file_name in files:
            if not file_name.lower().endswith(".psd"):
                continue
            full_path = os.path.join(root, file_name)
            rel_path = os.path.relpath(full_path, psd_root).replace("\\", "/")
            name_no_ext = os.path.splitext(file_name)[0]
            folder_tokens = tokenize(rel_path)
            size = None
            parser_used = "none"
            try:
                image = Image.open(full_path)
                size = image.size
                parser_used = "pillow"
                image.close()
            except Exception:
                size = None
            candidates.append(
                {
                    "fullPath": full_path,
                    "relativePath": rel_path,
                    "nameTokens": tokenize(name_no_ext),
                    "folderTokens": folder_tokens,
                    "size": size,
                    "parser": parser_used,
                }
            )
    return candidates


def score_psd_match(entry_tokens, entry_name, entry_size, entry_category, psd):
    token_score = token_overlap_score(entry_tokens, psd["folderTokens"])
    basename_a = " ".join(entry_name)
    basename_b = " ".join(psd["nameTokens"])
    fuzzy_score = difflib.SequenceMatcher(None, basename_a, basename_b).ratio() if basename_a and basename_b else 0.0

    dimension_score = 0.0
    if entry_size and psd["size"]:
        ew, eh = entry_size
        pw, ph = psd["size"]
        if ew == pw and eh == ph:
            dimension_score = 1.0
        elif ew > 0 and eh > 0 and pw > 0 and ph > 0:
            entry_aspect = float(ew) / float(eh)
            psd_aspect = float(pw) / float(ph)
            aspect_delta = abs(entry_aspect - psd_aspect)
            dimension_score = max(0.0, 1.0 - min(1.0, aspect_delta))

    folder_score = 0.0
    folder_text = psd["relativePath"].lower()
    if entry_category == "ui" and "gui" in folder_text:
        folder_score = 1.0
    elif entry_category == "level/tiles" and ("ground" in folder_text or "water" in folder_text or "tiles" in folder_text):
        folder_score = 1.0
    elif entry_category == "level/props" and ("object" in folder_text or "rock" in folder_text or "tree" in folder_text):
        folder_score = 1.0
    elif entry_category == "effects" and ("magic" in folder_text or "effect" in folder_text):
        folder_score = 1.0

    final_score = (0.55 * token_score) + (0.15 * fuzzy_score) + (0.20 * dimension_score) + (0.10 * folder_score)
    final_score = max(0.0, min(1.0, final_score))
    return final_score, token_score, fuzzy_score, dimension_score, folder_score


def find_psd_match(entry, psd_candidates):
    if not psd_candidates:
        return {
            "psdMatchStatus": "unmatched",
            "psdBestPath": None,
            "psdConfidence": 0.0,
            "psdParser": "none",
            "psdWidth": None,
            "psdHeight": None,
            "psdScoreBreakdown": {"token": 0.0, "fuzzy": 0.0, "dimension": 0.0, "folder": 0.0},
            "psdAlternatives": [],
            "psdStrategyVersion": "v1",
        }

    rel_source = entry.get("sourceRelative", "") or ""
    target_relative = entry.get("targetRelative", "") or ""
    base_name = os.path.splitext(os.path.basename(target_relative))[0]
    entry_tokens = tokenize((rel_source + " " + target_relative).lower())
    entry_name_tokens = tokenize(base_name)
    entry_size = (entry.get("imageWidth"), entry.get("imageHeight"))

    scored = []
    for psd in psd_candidates:
        score, token_score, fuzzy_score, dimension_score, folder_score = score_psd_match(
            entry_tokens, entry_name_tokens, entry_size, entry.get("category", "shared"), psd
        )
        scored.append(
            {
                "path": psd["fullPath"],
                "relativePath": psd["relativePath"],
                "confidence": round(score, 3),
                "breakdown": {
                    "token": round(token_score, 3),
                    "fuzzy": round(fuzzy_score, 3),
                    "dimension": round(dimension_score, 3),
                    "folder": round(folder_score, 3),
                },
                "parser": psd["parser"],
                "size": psd["size"],
            }
        )

    scored.sort(key=lambda item: (-item["confidence"], item["relativePath"]))
    best = scored[0]
    alternatives = []
    for alt in scored[:3]:
        alternatives.append({"path": alt["path"], "confidence": alt["confidence"]})

    if best["confidence"] >= 0.80:
        status = "matched"
    elif best["confidence"] >= 0.60:
        status = "matched"
    elif best["confidence"] >= 0.40:
        status = "ambiguous"
    else:
        status = "unmatched"

    if best["confidence"] < 0.40:
        best_path = None
        width = None
        height = None
    else:
        best_path = best["path"]
        width = best["size"][0] if best["size"] else None
        height = best["size"][1] if best["size"] else None

    return {
        "psdMatchStatus": status,
        "psdBestPath": best_path,
        "psdConfidence": best["confidence"],
        "psdParser": best["parser"],
        "psdWidth": width,
        "psdHeight": height,
        "psdScoreBreakdown": best["breakdown"],
        "psdAlternatives": alternatives,
        "psdStrategyVersion": "v1",
    }


def main():
    args = parse_args()
    manifest_path = os.path.abspath(args.manifest)
    output_path = os.path.abspath(args.output)
    overrides_path = os.path.abspath(args.overrides)

    manifest_entries = read_json(manifest_path)
    repo_root = resolve_repo_root(manifest_path)
    overrides = load_overrides(overrides_path)
    psd_candidates = collect_psd_candidates(args.psd_root)

    registry_entries = []
    for entry in manifest_entries:
        target_relative = entry.get("targetRelative")
        category = entry.get("category", "shared")
        if not target_relative:
            continue

        target_lower = target_relative.lower().replace("\\", "/")
        if not target_lower.endswith((".png", ".jpg", ".jpeg")):
            continue

        try:
            width, height = read_dimensions(repo_root, target_relative)
        except IOError:
            continue

        context_text = ("%s %s" % (entry.get("relativeSource", ""), target_relative)).lower()
        prefer_tiles = category == "level/tiles"
        cell_size = guess_cell_size(width, height, prefer_tiles)
        candidate = is_sheet_candidate(category, context_text, width, height)
        kind = infer_kind(category, context_text)
        confidence = compute_confidence(category, context_text, width, height, cell_size)
        include_auto_slice = candidate and confidence >= args.min_confidence

        asset_id = build_asset_id(target_relative)
        if not candidate:
            force_candidate = apply_overrides({"forceCandidate": False}, overrides, asset_id, target_relative).get("forceCandidate")
            if not force_candidate:
                continue
            candidate = True

        columns = max(1, width // cell_size)
        rows = max(1, height // cell_size)
        default_slice_mode = "tile_grid" if kind == "tile_sheet" else "animation_grid"

        base_entry = {
            "assetId": asset_id,
            "sourceRelative": entry.get("relativeSource"),
            "targetRelative": target_relative.replace("\\", "/"),
            "category": category,
            "inferredKind": kind,
            "sliceMode": default_slice_mode,
            "cellWidth": cell_size,
            "cellHeight": cell_size,
            "columns": columns,
            "rows": rows,
            "imageWidth": width,
            "imageHeight": height,
            "confidence": round(confidence, 3),
            "includeAutoSlice": include_auto_slice,
        }

        merged = apply_overrides(base_entry, overrides, asset_id, target_relative)
        if merged.get("cellWidth") and merged.get("cellHeight"):
            merged["columns"] = max(1, int(width) // int(merged["cellWidth"]))
            merged["rows"] = max(1, int(height) // int(merged["cellHeight"]))

        if "includeAutoSlice" in merged:
            merged["includeAutoSlice"] = bool(merged["includeAutoSlice"])
        else:
            merged["includeAutoSlice"] = include_auto_slice

        psd_match = find_psd_match(merged, psd_candidates)
        merged.update(psd_match)
        registry_entries.append(merged)

    registry_entries.sort(key=lambda item: item["assetId"])
    auto_slice_count = sum(1 for item in registry_entries if item.get("includeAutoSlice"))

    registry = {
        "generatedAtUtc": utc_now_iso(),
        "manifestPath": manifest_path,
        "overridesPath": overrides_path,
        "psdRoot": args.psd_root if os.path.isdir(args.psd_root) else None,
        "psdFileCount": len(psd_candidates),
        "entryCount": len(registry_entries),
        "autoSliceCount": auto_slice_count,
        "entries": registry_entries,
    }

    write_json(output_path, registry)
    print("Wrote registry with %d entries to %s" % (len(registry_entries), output_path))


if __name__ == "__main__":
    main()
